services:

  backend:
    build:
      context: ./backend
    container_name: weather_backend
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./data:/app/data
    env_file:
      - path: ./.env
        required: false
    restart: unless-stopped

  dashboard:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: weather_dashboard
    ports:
      - "8501:8501"
    env_file:
      - path: ./.env.frontend
        required: false
    depends_on:
      - backend
    restart: unless-stopped
